<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Access Dennie</title>
</head>
<body>

<h1>
    Access Dennie!
</h1>

<div class="col-3  text-center">
    <input class="btn btn-danger" id="addItemButton" data-mdb-ripple-color="dark" onclick="history.back()" value="Move Back" type="button">
</div>

</body>
</html>